server:
  port: 9093 # Port for the account-service

spring:
  application:
    name: admin-service # Name of the service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/