server:
  port: 9089 # Port for the userService

spring:
  application:
    name: transfer-service # Name of the service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka # URL of the Eureka Server