server:
  port: 9091 # Port for the loan-service

spring:
  application:
    name: loan-service # Name of the service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/