server:
  port: 8082 # Port for the account-service

spring:
  application:
    name: account-service # Name of the service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # URL of the Eureka Server
