server:
  port: 9092 # Port for the insuranceService

spring:
  application:
    name: insurance-service # Name of the service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka # URL of the Eureka Server